[[redirects]] 
 from = "/uniapi/*" 
 to = "https://be392405-5b88-4143-ad6b-f155b106ab85.bspapp.com/:splat" 
 status = 200 
 force = true 
 headers = {X-From = "Netlify"} 

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods =  "GET"
    Access-Control-Allow-Headers =  "X-Requested-With, Accept"
